// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emfxhergxhmrfodidpnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZnhoZXJneGhtcmZvZGlkcG5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTgwNTQsImV4cCI6MjA1ODM5NDA1NH0.wE4UrTBCmchp5Rw_6_CWcrZ0rrjHamVwym6O2M1WD7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);